// <auto-generated />
namespace TeamManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PopulateUsersTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PopulateUsersTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201709191255064_PopulateUsersTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
